### ISSUE TITLE
Crear archivos en la carpeta  ejercicios/javascript y realizar el ejercicio mencionado en el comentario

### ISSUE THREAD

**Issue by RoiVigo91** [gbtec-ext-alexandreinsua/bootcamp_fe#19]
crear archivos control-de-flujo.html y control-de-flujo.js en la carpeta ejercicios / javascript / 02-control-de-flujo 
        > y pegar el contenido correspondientte de ejercicios.js - pareja 8

**Comment by Valeriaterrone** [comment]
Listo!
